### ISSUE TITLE
Implementation of BODC Maps

### ISSUE THREAD

**Issue by androdnoc** [NOC-MDP/issue-tracking--polpred_offshore#2]
Lisa mentioned the use of BODC maps with bathymetry, which I assume is related to this map implementation?
* https://download.gebco.net/

I've done some digging in the code and they seem to use a library called Open Layers (more info [here](https://openlayers.org/)) which can use various sources for their map tiles.
I've looked into some options other than google maps in the past, as we are limited on how the google maps tiles are displayed (bathymetry looks a bit more sciencey). However, it has many features associated with it which are used within the app and boasts high performance and stability.
The other option I have come across previously is Leaflet (more info [here](https://leafletjs.com/)) which again allows multiple different map tiles types (bathymetry etc).

I will need to do more research to see if any of the other map options contain all of the functionality needed for the web application. If they do, we could make a case to change over the map interface for the web application (google maps also costs money!)

**To do:**
* Look into Leaflet and Open Layers as proposed alternatives to Google Maps
* Check specifically for map functionality.
* Look at potential layers to use for map tiles (bathymetry laters etc.)

_Feel free to discuss this further before any actions are made._

**Comment by NOC-ColinBell** [comment]
Probably worth looking into but I think Google Maps is a solid stable product and should remain our first choice for now.  Google Maps just uses a plain blue sea so I must admit it might be nice to somehow have different colours to represent depths over the oceans.  But its a low priority.

**Comment by androdnoc** [comment]
Following the meeting on 18.06, we have implemented the satellite view with google maps which has recieved positive feedback, I am happy to close this issue for now
