### ISSUE TITLE
Portal response to no model but in license area confusing

### ISSUE THREAD

**Issue by thopri** [NOC-MDP/issue-tracking--polpred_offshore#24]
When using the portal, I have noticed that if I select an point that is not covered by a model but is covered by a license. Example attached, the red point is actually outside the model domain.
<img width="948" alt="Screenshot 2020-07-14 at 08 10 06" src="https://user-images.githubusercontent.com/41162894/87396344-9994cf00-c5aa-11ea-878a-6c6903bfca58.png">
The portal returns a message saying no license applicable, which while true is confusing as its clearly inside the license area. So a better response would be to say outside of model domain. And ideally provide option to display model grid as an overlay.

API handles it by saying outside of model domain or on land so doesn't need any changes.

**Comment by androdnoc** [comment]
Thanks for pointing this out.

What should be the case and has been the case in previous builds is that the dialog displaying ``There are no selected licences applicable`` is grouped with a ``View More`` button. which opens a dialog specifying the error. This implementation has been used as there will be cases where users try to make a prediction where none of their multiple licences are applicable, and so an multiple errors for each individual licence need to be shown.

This will be added back in in the next wave of fixes.

**Comment by androdnoc** [comment]
Issue resubmitted to #28
