### ISSUE TITLE
Lat Lon export option

### ISSUE THREAD

**Issue by thopri** [NOC-MDP/issue-tracking--polpred_offshore#26]
Ok now its my wish list :)

It would be good to be able to pick multiple points, e.g. bring up model overlay and then select multiple cells the locations of which can be then exported in a txt or json format. At the moment I am using Delft Dashboard to create observation points which I then convert to lat lon before requesting in my API script for QA comparisons. While this works fine, I would like to be able to pick points based on existing lower resolution grids so I know that I am picking the correct points to compare, in theory I could build an existing model grid in Delft Dashboard and use that but would prefer to use our own system. :)

**Comment by androdnoc** [comment]
Created as seperate webpage. https://github.com/NOC-MDP/latlon-exporter
