### ISSUE TITLE
Elevation plot ripples (more noticeable at low interval predictions

### ISSUE THREAD

**Issue by thopri** [NOC-MDP/issue-tracking--polpred_offshore#30]
I have noticed that the plots for the Gulf and PG50 have "ripples" in them, this is probably due to the way plotly is drawing the lines. not major but would be nice to get them "smoothed"
![newplot-6](https://user-images.githubusercontent.com/41162894/87412801-5a25ad00-c5c1-11ea-86ac-c908ff4f3c14.png)

**Comment by androdnoc** [comment]
See #23 (Not detailed as I'm aware of issue and I know why it's the case lol), essentially graph values derived from data table shown in the ``data`` tab which have been rounded to 2dp. Graphs need to be updated to get data from API response. This is an important issue.
