### ISSUE TITLE
Prediction interval selection

### ISSUE THREAD

**Issue by thopri** [NOC-MDP/issue-tracking--polpred_offshore#31]
Its possible to select invalid prediction intervals, not a problem but when you do it says no applicable license as per #24 this is likely to be resolved by #28 but will need to be checked/tested to ensure a error message such as incorrect prediction interval is shown.

**Comment by androdnoc** [comment]
Yes you are correct, error response is ``must be one of the follwing values: 5, 6, 10, 12, 15, 20, 30 or 60.`` Will be updated in next wave of fixes

**Comment by androdnoc** [comment]
fixed in #28
