### ISSUE TITLE
unable to pick time series point once spatial prediction is made

### ISSUE THREAD

**Issue by thopri** [NOC-MDP/issue-tracking--polpred_offshore#34]
I wasn't able to select a time series/red pin point over a spatial prediction. Screenshots show that I can select points outside the actual prediction but since this is land its not that helpful! :)

![Screenshot 2020-07-22 at 07 45 47](https://user-images.githubusercontent.com/41162894/88143777-bb680480-cbef-11ea-93ae-0030ed837bd7.png)
![Screenshot 2020-07-22 at 07 45 53](https://user-images.githubusercontent.com/41162894/88143793-c15de580-cbef-11ea-9cbe-c294085db718.png)

I think a manual prediction would still work just the ability to select points on map is gone. Only way I was able to fix was to refresh page.

**Comment by androdnoc** [comment]
Fixed for elevation squares and current arrows
