### ISSUE TITLE
Default states for Data File output

### ISSUE THREAD

**Issue by androdnoc** [NOC-MDP/issue-tracking--polpred_offshore#8]
Current default states for preference when computation is made

![image](https://user-images.githubusercontent.com/45202929/83641746-d6ca7200-a5a5-11ea-9e9f-038be1bfb792.png)

Following POLPRED, UV components are off by default but I have made them on by default in Polpred Offshore, what do we think?

_Open to discussion_

**So Far:**
* Lisa thinks we should have UV components **off** by default as it's thought that many customers don't use these.

**Comment by NOC-ColinBell** [comment]
Lisa is probably right and as long as they can turn them on when they need them may as well go with Lisa on this one.

**Comment by androdnoc** [comment]
Updated preferences to have Current components hidden by default.
